services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./data:/var/lib/cassandra
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   cassandra-data:

networks:
    core_docker_network:
      external: true

