services:
  postgresql-1:
    image: postgres
    container_name: postgresql-1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # hostname: "0.0.0.0"
    ports:
      - "5432:5432"
    volumes:
      # check: docker exec postgresql-1 id
      - ./data:/var/lib/postgresql # required chown -R uid:uid path/dir
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   postgres-data:

networks:
    core_docker_network:
      external: true

