services:
  postgresql-1:
    image: postgres
    container_name: postgresql-1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/etc:/etc
      - ./data/var:/var
    restart: unless-stopped

# volumes:
#   postgres-data:
