services:
  postgresql-1:
    image: postgres
    container_name: postgresql-1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: "127.0.0.1"
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/foo/bar
    restart: unless-stopped

# volumes:
#   postgres-data:
