global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093 # compose service name

scrape_configs:
  # start core region
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          group: "monitoring"
  # end   core region

  # start backend region
  - job_name: "backend-probe-9001"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://172.17.0.1:9001/v1/check/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  # end   backend region

