services:
  prometheus-1:
    image: prom/prometheus
    container_name: prometheus-1
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "9090:9090"
    volumes:
      - ./data:/etc/prometheus
    networks:
      - core_docker_network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
        - /:/hostfs:ro,rslave
    command:
      - '--path.rootfs=/hostfs'
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   prometheus-data:

networks:
    core_docker_network:
      external: true

