services:
  prometheus-1:
    image: prom/prometheus
    container_name: prometheus-1
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "9090:9090"
    volumes:
      - ./data:/var/lib/cassandra
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   prometheus-data:

networks:
    core_docker_network:
      external: true

