services:
  prometheus-1:
    image: prom/prometheus
    container_name: prometheus-1
    # environment:
    #   FOO: ${FOO}
    # ports:
    #   - "3000:3000"
    volumes:
      - ./data/etc:/etc
      - ./data/var:/var
    restart: unless-stopped

# volumes:
#   prometheus-data:
