services:
  prometheus-1:
    image: prom/prometheus
    container_name: prometheus-1
    # environment:
    #   FOO: ${FOO}
    hostname: "127.0.0.1"
    ports:
      - "9090:9090"
    # volumes:
    #   - ./data:/foo/bar
    restart: unless-stopped

# volumes:
#   prometheus-data:
