services:
  grafana-1:
    image: grafana/grafana
    container_name: grafana-1
    # environment:
    #   FOO: ${FOO}
    # ports:
    #   - "3000:3000"
    volumes:
      - ./data/etc:/etc
      - ./data/var:/var
    restart: unless-stopped

# volumes:
#   grafana-data:
