services:
  grafana-1:
    image: grafana/grafana
    container_name: grafana-1
    # environment:
    #   FOO: ${FOO}
    hostname: "127.0.0.1"
    ports:
      - "3000:3000"
    # volumes:
    #   - ./data:/foo/bar
    restart: unless-stopped

# volumes:
#   grafana-data:
