services:
  kafka-1:
    image: apache/kafka
    container_name: kafka-1
    # environment:
    #   FOO: ${FOO}
    # ports:
    #   - "9092:9092"
    volumes:
      - ./data/etc:/etc
      - ./data/var:/var
    restart: unless-stopped

# volumes:
#   kafka-data:
