services:
  kafka-1:
    image: apache/kafka
    container_name: kafka-1
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "9092:9092"
    volumes:
      - ./data:/var/lib/kafka/data
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   kafka-data:

networks:
    core_docker_network:
      external: true

