services:
  rabbitmq-1:
    image: rabbitmq
    container_name: rabbitmq-1
    # environment:
    #   FOO: ${FOO}
    # hostname: "0.0.0.0"
    ports:
      - "5672:5672"
    volumes:
      - ./data:/var/lib/rabbitmq
    networks:
      - core_docker_network
    restart: unless-stopped

# volumes:
#   rabbitmq-data:

networks:
    core_docker_network:
      external: true

