services:
  redis-1:
    image: redis
    container_name: redis-1
    # environment:
    #   FOO: ${FOO}
    # ports:
    #   - "6379:6379"
    volumes:
      - ./data/etc:/etc
      - ./data/var:/var
    restart: unless-stopped

# volumes:
#   redis-data:
