services:
  redis-1:
    image: redis
    container_name: redis-1
    # environment:
    #   FOO: ${FOO}
    hostname: "127.0.0.1"
    ports:
      - "6379:6379"
    # volumes:
    #   - ./data:/foo/bar
    restart: unless-stopped

# volumes:
#   redis-data:
